org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false


# Mc stuff
minecraft_version = 1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.22

enabled_platforms = fabric,neoforge
pack_format_number = 24

# Mod stuff
mod_id = heartstone
mod_name = Heartstone
mod_version = 1.21-1.3.0
mod_license = Supplementaries Team License v.1.1
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar, Plantkillable
mod_description = Makes Farmer Villagers smarter!
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/heartstone
mod_github = https://github.com/MehVahdJukaar/heartstone
mod_credits = MehVahdJukaar

project_id = 573152


# Loaders
parchment_version = 1.20.6:2024.06.16

fabric_loader_version = 0.16.3
fabric_api_version = 0.103.0+1.21.1

neo_version = 21.1.13
neo_version_range = [4,)
loader_version_range = [4,)

# Other deps
moonlight_version = 1.21-2.17.15
moonlight_min_version = 1.21-2.14.12
cca_version = 5.2.1
trinkets_version = 3.7.0

